= beeLīn Java / JVM

This is the start of a DNSChain client for the JVM.

== Download and Install Prerequisites

[options="header",frame="all"]
|===
| | Mac OS X | Windows | Linux

| Prerequisites
| None - Java 8 is bundled inside the App. (Recent Mac OS X?)
| Java 8 w/StartCom certificate installed
| Java 8 w/StartCom certificate installed

| Binary download
| image:https://api.bintray.com/packages/beelin/beeLin-Releases/beeLin-java/images/download.svg[link="https://bintray.com/beelin/beeLin-Releases/beeLin-java/_latestVersion"]
| N/A - build from source is relatively easy, see below.
| N/A - build from source is relatively easy, see below.

|===

NOTE: **beeLin-java** is using HTTPS to query the DNSChain server at https://api.dnschain.net[api.dnschain.net] which uses a https://cert.startcom.org[StartCom] SSL certificate. By default, Java installations do not trust the StartCom certificate authority and your HTTPS connection to `api.dnschain.net` may fail. For more detail and instructions on how to install the StartCom certificate in your JDK/JRE see http://wernerstrydom.com/2014/01/14/installing-startcom-certificate-authority-certificates-java/[Installing StartCom Certificate Authority Certificates in Java].

== Build and run tests

    ./gradlew build

You can view the test results in `beelinj-lib/build/reports/tests/index.html`

Of course you probably want to install https://www.jetbrains.com/idea/download/[IntelliJ IDEA] to do this.

== Build and run the bare-bones browser

    ./gradlew :beelinj-browser-fx:run

== Build a self-contained JAR containing the browser

    ./gradlew :beelinj-browser-fx:shadowJar

To run the browser jar:

    java -jar beelinj-browser-fx/build/libs/beeLin.jar




